src/Entity/Transaction.php
<?php

namespace App\Entity;

use App\Repository\TransactionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TransactionRepository::class)
 */
class Transaction
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $crypto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $method;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $giveM;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $receiveM;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $txid;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;



    /**
     * @ORM\Column(type="boolean")
     */
    private $Ispaid;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCrypto(): ?string
    {
        return $this->crypto;
    }

    public function setCrypto(string $crypto): self
    {
        $this->crypto = $crypto;

        return $this;
    }

    public function getMethod(): ?string
    {
        return $this->method;
    }

    public function setMethod(string $method): self
    {
        $this->method = $method;

        return $this;
    }

    public function getGiveM(): ?string
    {
        return $this->giveM;
    }

    public function setGiveM(string $giveM): self
    {
        $this->giveM = $giveM;

        return $this;
    }

    public function getReceiveM(): ?string
    {
        return $this->receiveM;
    }

    public function setReceiveM(string $receiveM): self
    {
        $this->receiveM = $receiveM;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTxid(): ?string
    {
        return $this->txid;
    }

    public function setTxid(string $txid): self
    {
        $this->txid = $txid;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }



    public function getIspaid(): ?bool
    {
        return $this->Ispaid;
    }

    public function setIspaid(bool $Ispaid): self
    {
        $this->Ispaid = $Ispaid;

        return $this;
    }
}

src/Controller/UserPageController.php
<?php

namespace App\Controller;
use App\Entity\Actu;
use App\Entity\Shitcoin;
use App\Entity\Transaction;
use App\Form\BuyType;
use App\Form\SellType;
use App\Service\CallApi;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
class UserPageController extends AbstractController
{  private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/home', name: 'user_page')]
    public function index(CallApi  $api): Response
    {
        $crypto = $api->Content();

        $actu = $this->entityManager->getRepository(Actu::class)->findBy([],['id'=>'DESC'],'1');

        $shit = $this->entityManager->getRepository(Shitcoin::class)->findBy([],['id'=>'DESC'],'3');

        return $this->render('user_page/index.html.twig', [
            'crypto' => $crypto,
            'actu'=>$actu,
            'shit'=>$shit
        ]);
    }

    #[Route('/buy_sell', name: 'exchange')]
    public function exchange(CallApi  $api, Request $request): Response
    {
        $user = $this->getUser();

        $id= uniqid();


        $cu = $api->Content();


        $buy = new Transaction();
        $buyform = $this->createForm(BuyType::class, $buy,[
            'attr' =>
                [
                    'class'=>'currency_validate',
                    'name'=>'myform'
                ]
        ]);



        $buyform->handleRequest($request);
        if( $buyform->isSubmitted() &&  $buyform->isValid()){
             $buy =  $buyform->getData();
             $email = $user->getEmail();
            $buy->setType('achat');
            $buy->setEmail($email);
            $buy->setIspaid(false);
            $buy->setDate(new \DateTime('now'));



            $doctrine = $this->getDoctrine()->getManager();
            $doctrine->persist($buy);
            $doctrine->flush();

            return $this->redirectToRoute('exchange');


        }
        $sell = new Transaction();
        $sellform = $this->createForm(SellType::class, $sell,[
            'attr' =>
                [
                    'class'=>'currency2_validate',
                    'name'=>'myform'
                ]
        ]);



        $sellform->handleRequest($request);
        if( $sellform->isSubmitted() &&  $sellform->isValid()){

            $sell =  $sellform->getData();
            $email = $user->getEmail();


            $sell->setType('vente');
            $sell->setEmail($email);

            $sell->setIspaid(false);
            $sell->setDate(new \DateTime('now'));

             $sell->setTxid($id);

            $doctrine = $this->getDoctrine()->getManager();
            $doctrine->persist($sell);
            $doctrine->flush();

            return $this->redirectToRoute('exchange');


        }
        $transaction = $this->getDoctrine()->getRepository(Transaction::class)->findBy(array(), array('id' => 'desc'),1,0);



        return $this->render('user_page/exchange.html.twig', [
            'controller_name' => 'UserPageController',
            'crypto'=> $cu,
            'buy'=>$buyform->createView(),
            'transaction'=> $transaction,
            'sell'=>$sellform->createView(),
            'id'=>$id,
            'user'=>$user
        ]);
    }

    #[Route('/account', name: 'account')]
    public function account(): Response
    {
        $transaction = $this->getDoctrine()->getRepository(Transaction::class)->findAll();

        return $this->render('user_page/compte.html.twig', [
            'controller_name' => 'UserPageController',
            'transactions'=>$transaction
        ]);
    }

    #[Route('/setting', name: 'setting')]
    public function setting(): Response
    {
        return $this->render('user_page/repair.html.twig', [
            'controller_name' => 'UserPageController',
        ]);
    }
    /**
     * @Route("/logout", name="logout")
     */
    public function logout()
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/user_page/compte.html.twig
{% extends'base.html.twig' %}
{% block body %}
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>

    <div id="main-wrapper">

        <div class="header">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <nav class="navbar">

                            <div class="header-search d-flex align-items-center">

                            </div>


                            <div class="dashboard_log">
                                <div class="d-flex align-items-center">
                                    <div class="profile_log dropdown">
                                        <div class="user" data-toggle="dropdown">
                                            <span class="thumb"><i class="mdi mdi-account"></i></span>
                                            <span class="name">{{ app.user.email }}</span>
                                            <span class="arrow"><i class="la la-angle-down"></i></span>
                                        </div>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a href="{{ path('actu') }}" class="dropdown-item">
                                                <i class="mdi mdi-account"></i> actualité
                                            </a>
                                            <a href="{{ path('shit') }}" class="dropdown-item">
                                                <i class="la la-book"></i> Shitcoin
                                            </a>
                                            <a href="{{ path('contact') }}" class="dropdown-item">
                                                <i class="la la-cog"></i> contact
                                            </a>

                                            <a href="{{ path('logout') }}" class="dropdown-item logout">
                                                <i class="la la-sign-out"></i> Déconnexion
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        <div class="sidebar">
            <a class="brand-logo" href="{{ path('user_page') }}">
                <img src="/builder/images/logo.png" alt="">
                <span>CRYPTOBANk </span></a>
            <div class="menu">
                <ul>
                    <li>
                        <a href="{{ path('user_page') }}">
                            <span><i class="mdi mdi-view-dashboard"></i></span>
                            <span class="nav-text">accueil</span>
                        </a>
                    </li>
                    <li><a href="{{ path('exchange') }}">
                            <span><i class="mdi mdi-repeat"></i></span>
                            <span class="nav-text">Echange</span>
                        </a>
                    </li>
                    <li><a href="{{ path('account') }}">
                            <span><i class="mdi mdi-account"></i></span>
                            <span class="nav-text">Historique</span>
                        </a>
                    </li>
                    <li><a href="{{ path('setting') }}">
                            <span><i class="mdi mdi-settings"></i></span>
                            <span class="nav-text">Compte</span>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="sidebar-footer">
                <div class="social">
                    <a href="#"><i class="fa fa-youtube-play"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-facebook"></i></a>
                </div>
                <div class="copy_right">
                    © 2020 Quixlab
                </div>
            </div>

        </div>

        <div class="page_title">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="page_title-content">
                            <p>Welcome Back,
                                <span> {{ app.user.username }}</span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="content-body">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-header border-0">
                                <h4 class="card-title">Transaction History</h4>
                            </div>
                            <div class="card-body pt-0">
                                <div class="transaction-table">
                                    <div class="table-responsive">
                                        <table class="table mb-0 table-responsive-sm">
                                            <tbody>
                                            {% for transaction in transactions %}
                                                {% if transaction.type == 'vente' %}

                                                    <tr>
                                                        <td><span class="sold-thumb"><i class="la la-arrow-down"></i></span>
                                                        </td>

                                                        <td>
                                                            <span class="badge badge-danger">{{ transaction.type }}</span>
                                                        </td>
                                                        <td>
                                                            {{ transaction.crypto }}
                                                        </td>
                                                        <td>
                                                            {{ transaction.method }}
                                                        </td>
                                                        <td class="text-danger">{{ transaction.giveM }}</td>
                                                        {% if transaction.ispaid %}
                                                        <td> paye</td>
                                                        {% else %}
                                                            <td> en cours</td>
                                                        {% endif %}
                                                        <td> {{ transaction.date | date("H:m:s   d-m-Y") }}</td>
                                                    </tr>

                                                {% elseif transaction.type == 'achat' %}

                                                    <tr>
                                                        <td><span class="buy-thumb"><i class="la la-arrow-up"></i></span>
                                                        </td>
                                                        <td>
                                                            <span class="badge badge-success">{{ transaction.type }}</span>
                                                        </td>
                                                        <td>
                                                            {{ transaction.crypto }}
                                                        </td>
                                                        <td>
                                                            {{ transaction.method }}
                                                        </td>

                                                        <td class="text-danger">{{ transaction.receiveM }}</td>
                                                        {% if transaction.ispaid %}
                                                            <td> paye</td>
                                                        {% else %}
                                                            <td> en cours</td>
                                                        {% endif %}
                                                        <td> {{ transaction.date | date("Y-m-d H:m:s") }}</td>

                                                        {% endif %}
                                            {% endfor %}


                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>


    <script src="/builder/vendor/jquery/jquery.min.js"></script>
    <script src="/builder/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


{{encore_entry_script_tags('script')}}
{% endblock %}